### ISSUE TITLE
Error when a .py file is implied by a package but a .pyi file also exists

### ISSUE THREAD

**Issue by gvanrossum** [JukkaL/mypy#1047]
I have both p/x.py and p/x.pyi, as well as p/__init.py. When I start mypy as `mypy p/x.py`, things work fine. However when I start it as `mypy p` (using the folder support I added recently) or as `mypy --package p` (which Jukka added last month) I get a complaint about `Module p.x processed twice`.

Apparently it still tries to find p.x using module search, even though it found the file already when traversing the folder/package. It then adds the stub p/x.pyi to its list of things to do, even though the non-stub p/x.py is already in that list.

**Comment by gvanrossum** [comment]
I have a better theory. It's because the directory traversal finds both. It should prefer the .py over the .pyi I think? I'll make a PR.

**Comment by JukkaL** [comment]
It's not obvious which should take precedence. You could argue that if there are both a `.pyi` file and `.py` file in the same directory, the `.pyi` file should take precedence as otherwise the file would always be ignored by both mypy and Python and thus its existence would seem pointless. If mypy would give `.pyi` precedence then the story is pretty logical: Python uses the `.py` file and mypy uses the `.pyi` file.
