### ISSUE TITLE
don't call `exit` in report_internal_error

### ISSUE THREAD

**Issue by bcdarwin** [JukkaL/mypy#1080]
I'm getting an internal error.  The new `report_internal_error` gives me line numbers, but it's still a bit hard to figure out what's actually going on.  Before this procedure was introduced, I could load pdb and walk up the call stack to find some interesting variables and reduce to a minimal test case.  Now that doesn't work because the program terminates.  Probably better to just rethrow as InternalError("please report") or something?

**Comment by kirbyfan64** [comment]
Can't you just break at `report_internal_error` in pdb?

**Comment by bcdarwin** [comment]
There are workarounds, certainly.

**Comment by gvanrossum** [comment]
Maybe add a new command-line flag `--pdb` that throws you into pdb when an
internal error is reported?

**Comment by kirbyfan64** [comment]
[RPython actually does that](http://kirbyfan64.github.io/posts/the-magic-of-rpython.html#rpython-drops-you-some-neat-info): when an error occurs, it puts you inside a `pdb` debugging session.

**Comment by gvanrossum** [comment]
So does py.test. (But it's a flag -- many people wouldn't know what to do
in pdb or even how to get out of it. And the mypy unit tests run in a
subprocess with stdin/out/err connected to pipes.)

On Thu, Dec 17, 2015 at 10:55 AM, Ryan Gonzalez <notifications@github.com>
wrote:

> RPython actually does that
> <http://kirbyfan64.github.io/posts/the-magic-of-rpython.html#rpython-drops-you-some-neat-info>:
> when an error occurs, it puts you inside a pdb debugging session.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JukkaL/mypy/issues/1080#issuecomment-165547327>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by gvanrossum** [comment]
See PR #1086.

**Comment by gvanrossum** [comment]
I guess the one use case (real or imagined?) this doesn't cover would be if you have some *other* favorite debugger. Just setting a breakpoint at the `report_internal_error()` call site doesn't really help, since at that point the exception has already been caught. I guess the only solution would be to have another flag that causes it to re-raise the exception. But I'll wait until someone actually asks for that (it would be straightforward to add using the PR I just sent as a template).
