### ISSUE TITLE
Add support for SimpleNamespace

### ISSUE THREAD

**Issue by DanielShaulov** [JukkaL/mypy#1132]
The following code gives errors:

```python
from types import SimpleNamespace
ns = SimpleNamespace()
ns.a = 5
print(ns.a/2)
```

There are two ways to make this work:
* Treat it like a `Dict[str, Any]`. Allow all assignments and treat all reads as if they return `Any`.
* Track the first assignment and then treat it as that type. Reading before assignment is an error.

I haven't seen any of mypy's code, but the first sounds simpler. Although there should already be something similar to the second option for module level variables.

**Comment by JukkaL** [comment]
Hmm I've never used `SimpleNamespace`. However, it doesn't look to be much like `Dict[...]`. A potential way to define it in a stub is like this:

```
_base = None  # type: Any
class SimpleNamespace(_base): ...
```

This means that mypy would basically assume that it can have an arbitrary, unknown set of attributes, due to the `Any` base class.

The change would have to go to stubs which live in the typeshed repo. Would you mind creating an issue there (https://github.com/python/typeshed/issues)?

**Comment by DanielShaulov** [comment]
Hi, Thanks.
This works exactly like I meant in my first point.
A few questions:
* can I just directly inherit in the stub? (seems like it works)
```python
class SimpleNamespace(Any): ...
```
* Is there any way to make it work like in my second option? tracking the assignments and checking the types?

**Comment by gvanrossum** [comment]
Closing this, as it's a typeshed issue.
