### ISSUE TITLE
Name not defined errors accessing functions defined later in a function

### ISSUE THREAD

**Issue by timabbott** [JukkaL/mypy#1151]
This:
```
def test():
    def foo():
        return bar()

    def bar():
        return "bar"
```
Throws:
```
/home/tabbott/foo.py: note: In function "foo":
/home/tabbott/foo.py:6: error: Name 'bar' is not defined
```

**Comment by JukkaL** [comment]
A potential workaround is to change the order of nested functions, assuming that they aren't mutually recursive.

There should be a new pass when semantically analyzing function bodies. The first pass would analyze the body of the function but ignore the bodies of any nested functions. The second pass would only analyze bodies of nested functions. That way all the names defined in the enclosing scope would be defined, instead of just those that textually precede a function definition. These passes can be specific to each function instead of being file-level.

**Comment by timabbott** [comment]
Cool.  Yeah I already did that workaround for the cases I have in real code that aren't mutually nested, but I definitely have some parser code that is mutually nested.

**Comment by timabbott** [comment]
Another common case for this shows up in a lot of scripts:

```
def foo():
    # type: () -> None                                                                                                                   
    options.verbose


import optparse
parser = optparse.OptionParser()
parser.add_option('--verbose',
                  default=False,
                  help=optparse.SUPPRESS_HELP,
                  action='store_true')
(options, args) = parser.parse_args()
```

**Comment by JukkaL** [comment]
I'm going to give this a go.
