### ISSUE TITLE
Mypy error trying to annotate initialization of Dict[str, List[str]]

### ISSUE THREAD

**Issue by timabbott** [JukkaL/mypy#1166]
Reproducer:
`result = dict(x=[], y=[]) # type: Dict[str, List[str]]                                        `
Error:
`/home/tabbott/foo.py:3: error: Incompatible types in assignment (expression has type Dict[str, List[None]], variable has type Dict[str, List[str]])`

**Comment by gnprice** [comment]
Fascinating. I'm very curious what's going on underneath this.

... and now I understand! Took some poking, and I've preserved the comment as I started writing it along the way, in case it's interesting for others still figuring out this codebase. Discussion of the actual issue below

## Investigation

Slightly shorter reproducer: just one argument is enough:
`mypy -c 'r = dict(x=[]) # type: Dict[str, List[str]]'`

There's clearly something funny about the error message, because even if I annotate it as having `List[None]` it still fails, with this message:
```
$ mypy -c 'r = dict(x=[]) # type: Dict[str, List[None]]'
<string>:1: error: Incompatible types in assignment (expression has type Dict[str, List[None]], variable has type Dict[str, List[None]])
```
where both types appear to be the same.

I'm actually puzzled why we're able to typecheck constructing a `dict` this way at all -- the stub for `dict` has these constructors:
```
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, map: Mapping[_KT, _VT]) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[Tuple[_KT, _VT]]) -> None: ...  # TODO keyword args
```
complete with TODO comment. So we must be special-casing `dict` calls, but...

... aha, here's where we do so: https://github.com/jukkal/mypy/blob/master/mypy/semanal.py#L1716

But when I try with what I think is the expression that code analyzes this into, it no longer reproduces:
`mypy -c 'r = {"x": []} # type: Dict[str, List[str]]'`
So either I'm missing something about that translation, or there's a bug in it, or (what I think most likely) the `expr.analyzed` business isn't quite having the same effect somewhere as if the expression actually were that analyzed form in the first place.

## Actual issue, specifically

And aha. It seems like the gap between `expr.analyzed` and the real thing has to be around this bit of code: https://github.com/jukkal/mypy/blob/master/mypy/checkexpr.py#L123 and I was puzzled for a while at how that could be but then dug through some more layers, and I think I see the issue. That code goes and calls `self.accept`, which pushes a `None` onto the typechecker's stack of "type contexts". That in turn defeats `infer_function_type_arguments_using_context` so that it fails to have any effect: https://github.com/jukkal/mypy/blob/master/mypy/checkexpr.py#L334 By contrast if we didn't have that extra `accept` call in there, our "type context" would still be the one pushed by `check_simple_assignment`, which is the expected type of the variable taken here from the annotation, and `infer_function_type_arguments_using_context` would properly see that type and unify it with the generic type for the synthesized `DictExpr`, which is why initializing with `{"x": []}` works.

So one local band-aid fix that would handle this specific situation would be to replace that `self.accept(e.analyzed)` with `e.analyzed.accept(self)`, skipping the extra type context. Or perhaps to better match other code, `self.accept(e.analyzed, self.chk.type_context[-1])`.

## Actual issue, generally

I'm kind of worried about this `type_context` setup in general, though, now that I understand it. It feels to me like a bit of an ad-hoc way to be propagating type relationships up and down the expression tree. Here are some more examples that fail for similar reasons:
```
a = [] # type: List[int] # works
b = [] + [] # type: List[int]
c = [] + [1] # type: List[int]
d = set() # type: Set[int] # works
e = set().union(set()) # type: Set[int]
f = set().union({1,2}) # type: Set[int]
```
In each of these cases we don't propagate any type information down to the first collection mentioned, we decide to treat its type variable as `None`, and only then do we get to calling a method on it, and then the assignment. At one of these points (depending on the example) it becomes clear that that type variable should have been `int`, but it's too late -- we've already set it to `None`.

The line here between what currently works and what doesn't seems pretty subtle and tied to the specifics of how mypy is implemented -- it seems like it'd be pretty challenging to write down clearly what's permitted in good documentation and for users to understand it well enough not to be surprised.

A way that I'd love to be able to handle this kind of situation, which I think would help a lot in making the boundaries of what's allowed simpler for users to understand and for us to describe clearly, is this: We have some subexpressions whose types contain variables; the way the subexpressions combine puts constraints on those variables; and we combine those constraints to work out what the type variables should be. (So in my `b` example the two `[]` expressions have type `List[T1]`, `List[T2]` for fresh type variables `T1`, `T2`; then `List[T1].__add__` takes argument `List[T1]`, so `List[T2] <: List[T1]` which means `T2 == T1`, and it returns `List[T1]`; assignment has a similar constraint, so `List[T1] <: List[int]` which means `T1 == int`; and combining those we get `T1 == T2 == int`.) We already have some degree of constraint solving going on, for instance in the examples here that do work. @JukkaL, I'd love to hear your thoughts on what the limitations are of that system at present and what'd be required to be able to apply it somewhat more broadly. 

/cc @ddfisher as this is related to some things we've talked about this week.

**Comment by JukkaL** [comment]
@gnprice Mypy does type inference only using the immediate local context. This breaks down in some cases, as illustrated by your examples. Building constraints for a whole expression tree and solving them them in one go would make type inference more general, but it would also make it much more complex (and likely more expensive). Thing like overloading would be particularly tricky, and it would probably be more difficult to generate informative error messages. Also, the current approach seems to work pretty well for real-world code.

However, we could probably tweak things to work in more cases without having to totally rewrite the type inference logic. Mypy already has support for some common special cases where the basic algorithm breaks down. We could likely extend it to support things like an empty collection as the receiver in a method call (such as `[] + []`) without fundamentally altering the algorithm. It would be a little hacky, but it might still be worthwhile. 

Additionally, we could give better error messages when type inference fails that would help working around the limitations. Our documentation should also explain this better.

One of these things is usually the best way to work around type inference problems:

1) Refactor into multiple statements. Example:
```
t = [] # type: List[int]
b = t + []
```

2) Insert a cast. Example:
```
b = cast(List[int], []) + []
```
