### ISSUE TITLE
Cannot determine type Issue with near import loops

### ISSUE THREAD

**Issue by timabbott** [JukkaL/mypy#1185]
I ran into this trying to get the sqlalchemy stubs working.  The error is:

```
<string>:1: note: In module imported here:
typeshed/third_party/2.7/stest/__init__.pyi:4: error: Cannot determine type of 'Constraint'
```

Here's a reproducer zipped tar archive:
[foo.zip](https://github.com/JukkaL/mypy/files/108780/foo.zip)

**Comment by JukkaL** [comment]
This is a known problem (though there doesn't seem to be an open issue). If there are cyclic module dependencies, type inference often needs help because mypy does only a single type checking pass. 

In this particular case, you may want to rewrite cases like this:
```
Constraint = scheme.Constraint
```
into something like this:
```
from .scheme import Constraint as Constraint
```

Let me know if that works for you.

**Comment by timabbott** [comment]
That workaround worked for the sqlalchemy stubs; I had actually tried it before unsuccessfully, but I now suspect that was due to an unrelated problem.

**Comment by JukkaL** [comment]
Closing as this seems like a special case of #481.
