### ISSUE TITLE
Request: allow refinement types

### ISSUE THREAD

**Issue by ddzville** [JukkaL/mypy#560]
Please consider allowing:

```Refine[C, f]``` to be used as a type, where ```C``` is a type and ```f``` is consistent with: ```C -> bool```

This allows to capture and precisely document rich type constraints that the basic type system cannot express. 

e.g.

```BalancedTree = Refine[Tree, isBalanced]``` ## where  ```isBalanced : Tree -> bool```.

```def insert(item, tree: BalancedTree) -> BalancedTree: ```

The type checker need not do anything fancy with this, and can just treat it as ```Tree``` for type-checking purposes, possibly verifying that the refinement predicate ```isBalanced``` is consistent with  ```Tree -> bool```.

Slightly more ambitious: type checker could insist that calls to ```insert``` satisfy some form of statically determined exact match with ```Refine[Tree, isBalanced]```. 

Even more ambitious might allow ```And[isBalanced, isSmall]``` to be consistent with ```isBalanced```, and require this to type-check.

If run-time type checking is at some point made an option, the ```isBalanced``` would be checked.

**Comment by JukkaL** [comment]
Would these mostly be useful for documentation purposes, since these wouldn't be enforced statically? Or would the ultimate goal be to check these at runtime? Runtime checking is not easy to implement and it's out of the scope for mypy (at least for now).

Also, I'd like to see some non-trivial (code) examples of how these would be used in practice.

**Comment by ddzville** [comment]
Mostly documentation, so we can capture a large set of things otherwise left unsaid or left in comments.

Does the search tree / ```insert``` lack something you would want in an example? I could plug in AVL or Red-Black tree specifics if you want more details of possible bodies of the ```insert``` function.

**Comment by JukkaL** [comment]
I'm mostly interested in multiple, significant pieces of annotated code that uses an annotated library / libraries. Even code in another language with a similar feature would be useful. Many language features work splendidly in small, restricted examples but don't really scale to realistic programs. Picking some code from lib-python/ (in the mypy repo) and annotating it with the new syntax would be a good way to show that the feature works with examples that aren't cherry-picked to show the feature in the best possible light :)

My gut feeling is that this would make the types complex/verbose enough to affect readability, and most programmers might not use this feature. Also, having types that can't be checked statically could be confusing. However, some good examples may help me change my opinion.

In general, I'm reluctant to consider new features to mypy if it's not clear that the feature would be generally useful. A tool like mypy realistically has a bounded complexity budget, and we want to pick features with a good 'bang for buck'. Even fairly well-established features like structural subtyping are still in the planning stage, since we don't want to risk adding a half-baked feature to mypy that may be difficult to remove or modify later, after people have started depending on it in their own code.

**Comment by JukkaL** [comment]
Closing this since we don't have concrete use cases where this would be useful.

**Comment by fabianhjr** [comment]
Just adding some case studies for the sake of future reference.

Simple Examples:

1. [Insert Sort](http://ucsd-progsys.github.io/lh-workshop/04-case-study-insertsort.html)
2. [Lazy Queues](http://ucsd-progsys.github.io/liquidhaskell-tutorial/09-case-study-lazy-queues.html)
3. [Associative Maps](http://ucsd-progsys.github.io/liquidhaskell-tutorial/10-case-study-associative-maps.html)
4. [AVL](http://ucsd-progsys.github.io/liquidhaskell-tutorial/12-case-study-AVL.html)
5. [Pointers 1](http://ucsd-progsys.github.io/liquidhaskell-tutorial/11-case-study-pointers.html)
6. [Pointers 2](http://ucsd-progsys.github.io/lh-workshop/06-case-study-bytestring.html)

> And speaking of “refining”, back in the land of type systems, refinement types (as used in LiquidHaskell) pair types with predicates that are guaranteed to hold for instances of the “refined” type.
[Are there alternatives to types for static analysis?](https://softwareengineering.stackexchange.com/a/309818/34217)

About projects using Refinement Types, it seems like scala-refine is the only refinement types library with a bit of traction: https://github.com/fthomas/refined/wiki/Built-with-refined

_Personal note_: It seems that refinement types are filling the niche of explicitly typing design contracts, or preconditions and postconditions. (See [Design by Contract](https://www.wikiwand.com/en/Design_by_contract))

**Comment by leonardo-m** [comment]
See also: https://ranjitjhala.github.io/static/refinement_types_for_typescript.pdf

**Comment by JosXa** [comment]
[ReSharper annotations](https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html) are also very well integrated in the C# ecosystem.

**Comment by pschanely** [comment]
[CrossHair](https://github.com/pschanely/CrossHair) is a design-by-contract static analysis tool for Python that fits solidly in the solution space here. (disclaimer: I am the core dev)

It supports a variety of syntaxes, and now with [typing.Annotated](https://www.python.org/dev/peps/pep-0593), in theory we could write refinements and have CrossHair check them. Reach out if you want to collaborate!

**Comment by hauntsaninja** [comment]
I believe mypy on master should mostly support (draft) PEP 647

**Comment by pschanely** [comment]
Neat; I was unfamiliar with [PEP 647](https://www.python.org/dev/peps/pep-0647/)!

For others looking at this with a refinement type lens: this PEP doesn't (and isn't trying to) increase the expressiveness of the type system. It is a way to tell the type checker that after certain user-defined functions return true on a value, it may narrow the type of that value. But this narrowing is just stuff like `List` to `List[str]`. In other words, to clarify, what's expressible in the type system isn't changing.

**Comment by alcides** [comment]
This can be achieved using the Annotated (PEP593) type (like @pschanely mentioned).

I am actually using this with refinements for program synthesis (using grammars with refined types). CrossHair or mypy support would help in our project as well (although we do not depend much on verification).

**Comment by espetro** [comment]
Hi everyone! I've created a [pretty simple library for refinement types](https://github.com/espetro/refined), by making use of PEP 647 (Type guards) and PEP 593 (Annotated types).

Currently, it only works for functions with a `@refined` decorator, but I'd love to get it to support mypy and other type checkers. Contributions are more than welcome! 😊 🍻
