### ISSUE TITLE
"# type: ignore" does not seem to work on multiline dicts

### ISSUE THREAD

**Issue by josephharrington** [JukkaL/mypy#627]
There seems to be inconsistent behavior between these two equivalent pieces of code.

mypy is happy with this:
```python
import http.client
errors = {'not_found': http.client.NOT_FOUND}  # type: ignore
```

but this fails with `"module" has no attribute "NOT_FOUND"` (no matter where I put the annotation):
```python
import http.client
errors = {                              # type: ignore
    'not_found': http.client.NOT_FOUND  # type: ignore
}                                       # type: ignore
```

**Comment by JukkaL** [comment]
Thanks for reporting this! I think the reason is that mypy only recognizes ignore annotations on the last line of a statement, which is clearly broken. 

I think that there are also some other cases where `# type: ignore` might not work correctly. The feature is still going to need a bit more love :-) If you spot any other cases where it behaves strangely, please report them since this is a pretty important feature.

**Comment by JukkaL** [comment]
Your example should now works like this:

```python
import http.client
errors = {
    'not_found': http.client.NOT_FOUND  # type: ignore
} 
```

The `# type: ignore` comment should be put on the line that the error refers to. This way we can only ignore parts of a multi-line statement, which can be useful in cases such as large dict literals.

**Comment by gvanrossum** [comment]
Do you think we should specify this in the PEP? Or is this a mypy "extra"?
