### ISSUE TITLE
Cannot parse destructuring in lambda arguments

### ISSUE THREAD

**Issue by MichalPokorny** [JukkaL/mypy#746]
```
adder = lambda (x, y): x + y
```
=> `error: Parse error before (`

**Comment by o11c** [comment]
I'm working on it, but probably will *only* support it for the parse step, not for analysis.

**Comment by JukkaL** [comment]
This can also be used in regular function definitions (#785). This is a Python 2 only feature.

**Comment by gnprice** [comment]
Merging information from a duplicate of this issue: in #934, @jhance proposed handling this by a desugaring, and @JukkaL and I both agreed that that's a good solution.

A v1 of that solution will probably mean confusing error messages if a desugared parameter ends up involved in an error, but we all felt that's an acceptable tradeoff because the construct is so rarely used.

**Comment by JukkaL** [comment]
This works now.
