### ISSUE TITLE
Add Python 2 mode to mypy.stubgen

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#758]
Should be pretty easy at least for Python modules. It would be something like this:

```
$ python3 -m mypy.stubgen --py2 modname
```

**Comment by o11c** [comment]
As I mentioned briefly in  #724 (which also wants your feedback), `mypy.stubgen` should be treated as an entirely separate library from the `mypy` proper (i.e. it should become a package containing a `__main__.py` module).

It is entirely feasible that, in conjunction with my new `mypy.syntax` library and the existing `mypy.codecs` library (neither of which depends on anything else in mypy, with the exception of `mypy.syntax.lowering`). Of course, this would requiring rewriting stubgen to operate on raw parse trees instead of cooked AST node.

Of course, for pure-python libraries it it certainly possible to run the parser in python2 mode even when running under python3, or (at least with mine) vice versa, and it would be possibly to just port `mypy.stubgen.stubgenc` and not `mypy.stubgen.stubgenpy`.

Unlike some of your recent patches (mumble mumble), neither my open `driver` PR nor my local `syntax` work should conflict with refactoring `stubgen`'s internals.

**Comment by JukkaL** [comment]
Yeah, refactoring stubgen to be a separate tool that just depends on some other libraries within mypy would be good idea. The Python 2 support to (Python) stubgen however should be a small local change and should be easy to merge to parallel workstreams.
