### ISSUE TITLE
Rename builtins to __builtin__ in Python 2

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#987]
This is a little painful to change as we refer to `builtins` all over the place.

**Comment by gvanrossum** [comment]
One bizarre consequence of this is that using six in PY2 code causes a flurry of complaints about the various built-in classes (object, int, etc.). This seems caused by this line in typeshed/third-party/2.7/six/__init__.pyi:
```
from __builtin__ import unichr as unichr
```
It finds the __builtin__.pyi stub file but mypy has already read the builtins.pyi stub file and doesn't like the redefinitions. Some sample error messages:
```
/Users/guido/src/mypy/typeshed/builtins/2.7/__builtin__.pyi: note: In class "object":
/Users/guido/src/mypy/typeshed/builtins/2.7/__builtin__.pyi:31: error: Argument 1 of "__eq__" incompatible with supertype "object"
/Users/guido/src/mypy/typeshed/builtins/2.7/__builtin__.pyi:31: error: Return type of "__eq__" incompatible with supertype "object"
```
(similar errors are repeated for all methods and classes).

**Comment by JukkaL** [comment]
Increasing priority as this breaks stubs.

**Comment by JukkaL** [comment]
A workaround would be to use a tweaked `six` stub for now that targets `builtins` instead of `__builtin__`.
